/*
 * Este programa é um software livre; você pode redistribuí-lo e/ou 

    modificá-lo dentro dos termos da Licença Pública Geral GNU como 

    publicada pela Fundação do Software Livre (FSF); na versão 2 da 

    Licença.

 */
package br.groupfive.massaerosao;

import java.io.*;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Daniela Marques de Morais
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    String ip = System.getProperty("myapplication.ip");
    String url = "http://" + ip + "/projects/mysite/";
   
    public JanelaPrincipal(){
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogo = new javax.swing.JPanel();
        jPanelLeitura = new javax.swing.JPanel();
        jButtonCartaoSD = new javax.swing.JButton();
        jButtonBanco = new javax.swing.JButton();
        jPanelTempoReal = new javax.swing.JPanel();
        jButtonGraficos = new javax.swing.JButton();
        jButtonWeb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Massa e Erosão");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeitura.setBorder(javax.swing.BorderFactory.createTitledBorder("Leitura"));

        jButtonCartaoSD.setText("Cartão SD");
        jButtonCartaoSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCartaoSDMouseClicked(evt);
            }
        });

        jButtonBanco.setText("Banco de Dados");
        jButtonBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBancoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeituraLayout = new javax.swing.GroupLayout(jPanelLeitura);
        jPanelLeitura.setLayout(jPanelLeituraLayout);
        jPanelLeituraLayout.setHorizontalGroup(
            jPanelLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeituraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCartaoSD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanelLeituraLayout.setVerticalGroup(
            jPanelLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeituraLayout.createSequentialGroup()
                .addComponent(jButtonCartaoSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButtonBanco)
                .addContainerGap())
        );

        jPanelLogo.add(jPanelLeitura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        jPanelTempoReal.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo Real"));

        jButtonGraficos.setText("Índices/Gráficos");
        jButtonGraficos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGraficosMouseClicked(evt);
            }
        });

        jButtonWeb.setText("Via web");
        jButtonWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonWebMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTempoRealLayout = new javax.swing.GroupLayout(jPanelTempoReal);
        jPanelTempoReal.setLayout(jPanelTempoRealLayout);
        jPanelTempoRealLayout.setHorizontalGroup(
            jPanelTempoRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTempoRealLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTempoRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelTempoRealLayout.setVerticalGroup(
            jPanelTempoRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTempoRealLayout.createSequentialGroup()
                .addComponent(jButtonGraficos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonWeb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLogo.add(jPanelTempoReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, -1));

        getContentPane().add(jPanelLogo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGraficosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGraficosMouseClicked
        Graficos grafico = new Graficos();
        grafico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        grafico.setAlwaysOnTop(true);
        
        grafico.setResizable(false);
        grafico.pack();
        grafico.setVisible(true);
    }//GEN-LAST:event_jButtonGraficosMouseClicked

    private void jButtonWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonWebMouseClicked
        try {
            methodTry();
        } catch (URISyntaxException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonWebMouseClicked

    private void methodTry() throws URISyntaxException{
        try {
                java.awt.Desktop.getDesktop().browse( new java.net.URI(url) );
            } catch (IOException ex) {
                Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void jButtonCartaoSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCartaoSDMouseClicked
        LeituraArquivo ler = new LeituraArquivo(1);
        ler.setVisible(true);
    }//GEN-LAST:event_jButtonCartaoSDMouseClicked

    private void jButtonBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBancoMouseClicked
       
        LeituraBD ler = new LeituraBD();
        ler.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ler.setVisible(true);
       
    }//GEN-LAST:event_jButtonBancoMouseClicked

   
    public static void main() {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBanco;
    private javax.swing.JButton jButtonCartaoSD;
    private javax.swing.JButton jButtonGraficos;
    private javax.swing.JButton jButtonWeb;
    private javax.swing.JPanel jPanelLeitura;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelTempoReal;
    // End of variables declaration//GEN-END:variables
}
